---
title: "Intro Datenanalyse mit R"
author: "Jan-Philipp Kolb"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  beamer_presentation: 
    colortheme: dolphin
    fonttheme: structuresmallcapsserif
    highlight: espresso
    theme: Dresden
  pdf_document: 
    keep_tex: yes
    toc: yes
  slidy_presentation: 
    css: mycss.css
    keep_md: yes
---

# Warum R nutzen

```{r child = 'WarumR.Rmd'}
```

# Dein Freund das GUI

```{r child = 'FreundGUI.Rmd'}
```


```{r child = '../tutorial/Aufgabe_Vorbereitung.Rmd'}
```

# Grundlagen im Umgang mit der Sprache R

```{r child = 'GrundlagenR.Rmd'}
```


```{r child = '../tutorial/Aufgabe_Zuweisung.Rmd'}
```

# Datentypen und Indizieren

```{r child = 'Datentypen.Rmd'}
```

# Wie bekommt man Hilfe?

```{r child = 'Hilfe.Rmd'}
```

# Modularer Aufbau von R


```{r child = 'ModularerAufbau.Rmd'}
```


```{r child = '../tutorial/Aufgabe_Zusatzpakete.Rmd'}
```


# Datenimport 

```{r child = 'Import.Rmd'}
```


```{r child = '../tutorial/Aufgabe_Datenimport.Rmd'}
```


#  Datenexport 

```{r child = 'Export.Rmd'}
```

#  Datenanalyse 


```{r child = 'Datenanalyse.Rmd'}
```


```{r child = '../tutorial/Aufgabe_Apply.Rmd'}
```


# Einfache Grafiken

```{r child = 'EinfacheGrafiken.Rmd'}
```


```{r child = '../tutorial/Aufgabe_Barplot.Rmd'}
```


# Zusammenhang 

```{r child = 'Multidimensional.Rmd'}
```

# Das lattice Paket 

```{r child = 'LatticePaket.Rmd'}
```


```{r child = '../tutorial/Aufgabe_OECDdata.Rmd'}
```
