---
title: "Datenanalyse1"
author: "Jan-Philipp Kolb"
date: "10. April 2015"
output: html_document
---

Der Code zu diesem Teil befindet sich im R-file:

<https://github.com/Japhilko/IntroR/blob/master/2015/rcode/IntroR_C_ApplyFamilie.R>

```{r, echo=FALSE}
ab <- rnorm(100)

var(ab)

sd(ab)

min(ab)

max(ab)

range(ab)
```

# Fahlende Werte

```{r,eval=F}

  # fehlenden Wert einsetzen

ab[10] <- NA

var(ab)

  # hier muss ein weiteres Argument mitgegeben werden

var(ab,na.rm=T)

```

# Werte tabellieren

```{r,eval=F}
x <- sample(1:10,100,replace=T)

table(x)

musician <- sample(c("yes","no"),100,replace=T)

  # Zweidimensionale Häufigkeitstabelle
table(x,musician)

data(esoph)
table(esoph$agegp)


  # relative Häufigkeiten

table(esoph$agegp,esoph$alcgp)
?prop.table
prop.table(table(esoph$agegp,
                 esoph$alcgp),1)
```

# Funktion aggregate

```{r,eval=F}

?aggregate

  # Achtung das by Argument muss eine Liste sein
aggregate(state.x77,by=list(state.region),mean)
          
```

# Funktion apply

```{r,eval=F}

  # Beispieldatensatz
  # runif erzeugt gleichverteilte Zufallszahlen
ApplyDat <- cbind(1:4,runif(4),rnorm(4))

  # Mittelwerte pro Reihe
apply(ApplyDat,1,mean)

  # Mittelwerte pro Spalte
apply(ApplyDat,2,mean)

apply(ApplyDat,1,var)
apply(ApplyDat,1,sd)
apply(ApplyDat,1,range)
apply(ApplyDat,1,length)

```

# Funktion tapply


```{r,eval=F}

ApplyDat <- data.frame(Income=rnorm(5,1400,200),
                       Sex=sample(c(1,2),5,replace=T))

ApplyDat

tapply(ApplyDat$Income,ApplyDat$Sex,mean)

tapply(ApplyDat$Income,
       ApplyDat$Sex,function(x)x)
```


Die Daten zur apply Aufgabe befinden sich auch im github Verzeichnis.


## Weitere Quellenangaben:

Skript fur die ersten Schritte:

<http://www.stamats.de/InstallationUndErsteSchritteMitR.pdf>

Einfuhrung direkt auf CRAN:

<http://cran.r-project.org/doc/contrib/Sawitzki-Einfuehrung.pdf>




