---
title: "Datenanalyse"
author: "Jan-Philipp Kolb"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: beamer_presentation
---

```{r setupdatenanalyse, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache=T,warning=F,message = F)
```

## Die Daten einlesen

```{r importmzdata}
static_link <- "http://www.statistik.at/web_de/static/"
file <- "mz_2013_sds_-_datensatz_080469.sav"
dat <- rio::import(paste0(static_link,file),
                   to.data.frame=T)
```

## Einen Überblick über die Daten bekommen

```{r,eval=F}
head(dat)
```

```{r,echo=F}
library(knitr)
kable(head(dat))
```

## Einen ersten Eindruck der Daten bekommen

```{r}
library(dplyr)
glimpse(dat)
```

## Indizieren 

### Nur die erste Spalte

```{r,eval=F}
dat[,1]
```

```{r,echo=F}
head(dat[,1])
```

### Gleiches Ergebnis

```{r,eval=F}
dat$asbhh
```

```{r,echo=F}
head(dat$asbhh)
```

## Eine Beobachtung anschauen

### Nur die erste Reihe

```{r,eval=F}
dat[1,]
```

```{r,echo=F}
head(dat[1,])
```

### Die ersten vier Elemente der ersten Reihe

```{r}
dat[1,1:4]
```

## Die Daten zusammenfassen

```{r}
summary(dat$xnachbar)

```

